---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  labels:
    app.kubernetes.io/version: "1"
    owner: emjpm-portail
    team: emjpm-portail
  name: prod-pjm
  namespace: emjpm-portail
spec:
  rules:
    - host: pjm.social.gouv.fr
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
            path: /
  tls:
    - hosts:
        - pjm.social.gouv.fr
      secretName: pjm-certificate
