language: node_js

node_js:
- stable

cache:
  directories:
  - node_modules

script:
- yarn --frozen-lockfile
- yarn lint
- yarn build
- yarn export
- touch out/.nojekyll

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  on:
    branch: master
env:
  global:
    secure: fFYG46ba+pnagUVDQecgK64xsyEb3GhmSfB/B6DEKBLd01ZZ0JAmgAPPqXiVYjn2APITlbzEu+tsQX3YcDCT58Sbw4CU9NBTM1pyHdsTj2m7nk9LP50tff8AzyI98XxZoNOk2O2qVeIgiRoXPwoBpqMZ2ESjRxnxD22EyXVthP4lgZzNu6N2w1GGxLRCKbXOoC5KTgdVPkBh3RNn4XAaVvq0lWNaF27t9uRmFKfe5XRM2aHMVKCAieE2LDuklVMzoKHqy/zny6c/FPltttOBkDKvfA0oxdQeLV5e4PvWfcdtfjKLTXTXX3qUuzdP8HES+MlQSw+UnJLdLvEutVd92SKjl5Gx15T4S7pIQtsqBs9IHSO4tw0dmq+kvXEZYuc4bcUK1tfACzYAgLPfHwAkGbwb9sNdDYVD0JxRyfOiV759eRIhjw2afeMh7b1JaERZZBsRBgmCFDZd2poJZa7jD/m6awU+TBaRzRq11V3/rLYsSUxBoWIWgnsWqtk67mNJoUoumhOoZnSClSn3w56tdwsxCUo4XCc04ldEJOfTynrO2SEAw3UvVQFfFbuOdR1FHWltg/CaprSF6gyhB6aHYdHP5dY1FoS15iO0o+pzycI5zJXHuM1h1hDL1RWRy4HfndTQn7ghKsWJpI9s+VZPxWPinCZduncHJ3iwUv5aKE4=
