---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  labels:
    app: emjpm-portail
    owner: emjpm-portail
    team: emjpm-portail
  name: redirect
  namespace: emjpm-portail
spec:
  rules:
    - host: pjm.social.gouv.fr
      http:
        paths:
          - backend:
              serviceName: emjpm-portail
              servicePort: 80
            path: /
  tls:
    - hosts:
        - pjm.social.gouv.fr
      secretName: redirect-crt
